name: jara_market
description: Jara Market Vendor App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  get: ^4.7.2
  overlay_kit: ^1.1.2
  shared_preferences: ^2.5.3
  http: ^1.4.0
  mime: ^2.0.0
  pull_to_refresh_flutter3: ^2.0.2
  flutter_svg: ^2.1.0
  circular_countdown_timer: ^0.2.4
  image_picker: ^1.1.2
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Mont-ExtraLightDEMO.otf
        - asset: assets/fonts/Mont-HeavyDEMO.otf
