name: jara_market
description: Jara Market Vendor App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Mont
      fonts:
        - asset: assets/fonts/Mont-ExtraLightDEMO.otf
        - asset: assets/fonts/Mont-HeavyDEMO.otf
